version: "3.9"

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
      - AllowedHosts__0=http://localhost:9100
      - AllowedHosts__1=https://localhost:9100
  frontend:
    #Do not share secrets with environment, will be sendt in clear text to the clients browser
    environment:
      - BACKEND_URL=http://localhost:9000
