version: '3.9'

services:
  backend:
    build:
      context: ../WebApi
    restart: always
    container_name: webapi
    ports: 
      - 9000:80

  frontend:
    build:
      context: ../WebApp
    restart: always
    container_name: webapp
    ports: 
      - 9100:80