version: '3.9'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
      - AllowedHosts__0=http://localhost:9100
      - AllowedHosts__1=https://localhost:9100
  frontend:
    build:
      context: ../WebApp
      args:
        - API_URL=http://localhost:9000