name: build-and-test

on: [pull_request]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies for WebApi
        working-directory: ./WebApi
        run: dotnet restore
      - name: Build WebApi
        working-directory: ./WebApi
        run: dotnet build --configuration Release --no-restore
      - name: Test WebApi
        working-directory: ./WebApi
        run: dotnet test --no-restore --verbosity normal
      - name: Install dependencies for WebApp
        working-directory: ./WebApp
        run: npm ci
      - name: Build Angular app
        working-directory: ./WebApp
        run: npm run build:prod
      # - name: Test
      #   working-directory: ./WebApp
      #   run: npm test